name: Check answer & add label

on:
  pull_request:
    paths-ignore:
      - "README.md"

jobs:
  check_answer:
    name: Check Answer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check answer
        run: npm i && npm run check
  give_label:
    name: Add Label
    environment: Actions
    runs-on: ubuntu-latest
    needs: check_answer
    steps:
      - name: Add label
        uses: upinetree/labeler@fix-pull-request-param
        with:
          add-labels: "hacktoberfest-accepted"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          ignore-if-assigned: false
          ignore-if-labeled: true
