name: Check answer

on:
  pull_request:
    paths-ignore:
      - "README.md"

jobs:
  check_answer:
    name: Check Answer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check answer
        run: npm i && npm run check
